-- epi_shaoxing.dict_hbsag definition

CREATE TABLE `dict_hbsag` (
  `typecode` varchar(2) DEFAULT NULL,
  `typename` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- epi_shaoxing.dict_idcardtype definition

CREATE TABLE `dict_idcardtype` (
  `typecode` varchar(2) DEFAULT NULL,
  `typename` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- epi_shaoxing.dict_productno definition

CREATE TABLE `dict_productno` (
  `productno` varchar(2) DEFAULT NULL,
  `productno_cn` varchar(4) DEFAULT NULL,
  `productfullname` varchar(100) DEFAULT NULL,
  `productname` varchar(50) DEFAULT NULL,
  `productenname` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- epi_shaoxing.dict_regtype definition

CREATE TABLE `dict_regtype` (
  `typecode` varchar(2) DEFAULT NULL,
  `typename` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- epi_shaoxing.dict_sex definition

CREATE TABLE `dict_sex` (
  `sexcode` varchar(1) DEFAULT NULL,
  `sexname` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- epi_shaoxing.dict_ymbact definition

CREATE TABLE `dict_ymbact` (
  `FBACTID` varchar(4) DEFAULT NULL,
  `FBACTALIAS` varchar(50) DEFAULT NULL,
  `FBACTSHORTNAME` varchar(50) DEFAULT NULL,
  `FBACTENNAME` varchar(50) DEFAULT NULL,
  `FBACTSEQNAME` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- epi_shaoxing.dict_ymname definition

CREATE TABLE `dict_ymname` (
  `YMCODE` varchar(4) DEFAULT NULL,
  `YMNAME` varchar(50) DEFAULT NULL,
  `YMFULLNAME` varchar(130) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- epi_shaoxing.download_data definition

CREATE TABLE `download_data` (
  `DATATYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `QUERYPARA` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `STRSYSDATETIME` datetime DEFAULT NULL,
  `ENDDATETIME` datetime DEFAULT NULL,
  `SIGN` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JSON` longblob,
  `UUID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `NOWTOKEN` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  KEY `select_key` (`SIGN`,`DATATYPE`) USING BTREE,
  KEY `update_key` (`NOWTOKEN`,`ENDDATETIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_aefi definition

CREATE TABLE `epi_aefi` (
  `ID` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `REACTION_DATE_TIME` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DISCOVERY_DATE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FEVER` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SWELLING` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `LOCAL_INDURATION` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PATIENT_REFERRAL_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REPORT_DATE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REPORTING_UNIT_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SURVEY_DATE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PRE_CLASS_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REACTION_CLASS_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIN_CLINICAL_DIAGNOSTIC_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `RESPONSE_OBTAIN_MODE_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IS_CASE_STUDY` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IS_AEFI` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GROUP_AEFI_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_childinfo definition

CREATE TABLE `epi_childinfo` (
  `UNITCODE` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UNITNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SUPCODE` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CHILDNO` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IMUNO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PWD` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `NAME` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTH` datetime DEFAULT NULL,
  `SEX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BLOODTYPE` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REGTYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DWELLADDR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `COMADDR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FATHERNAME` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOTHERNAME` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FATHERUNIT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOTHERUNIT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOBPHONE` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `OTHERPHONE` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTHHOS` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTHDR` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CARDUNITCODE` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CARDDATE` datetime DEFAULT NULL,
  `BOOKINGDATE` datetime DEFAULT NULL,
  `CARDSUMNO` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `INSMONEY` decimal(6,2) DEFAULT NULL,
  `MHBSAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHBSAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBEAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BCGSCAR` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ALLERGY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TABU` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SMSTAG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `PHONETAG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TRANSCOUNT` decimal(3,0) DEFAULT '0',
  `TRANSTIME` datetime DEFAULT NULL,
  `remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `REGADDR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JWH` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SFJJ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `QHJZ` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CBANK` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INSP` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CSTATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CUPDATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TABUBACT` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `COUNTYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `QCJZ` datetime DEFAULT NULL,
  `BASECODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FATHERID` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOTHERID` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CID` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `STATIONCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CITYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `WEIGHT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBSAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBCAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBEAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTHNO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHILDNO` char(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FIMMUBILL` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIMMUGRANTDATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIMMUGRANTSTATIONCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIMMUGRANTSTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JOB_ID` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SERVERUPDATETIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `FPROOFGRANTDATE` datetime DEFAULT NULL,
  `FOUTOFPROVINCE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `STATUSTIME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIsAdult` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否为成人  1(是)，0(否)',
  `FChildFromCard` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '儿童基本信息是否来自于IC卡  1(是)，0(否)',
  `FGestationalWeeks` decimal(5,1) DEFAULT NULL,
  `FNETHEALTHID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '电子健康卡唯一标识',
  `FMOTHERIDCARDTYPE` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '母亲身份证件类型',
  `FMOTHERIDCARDTYPETEXT` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '母亲身份证件类型名称',
  `FFATHERIDCARDTYPE` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '父亲身份证件类型',
  `FFATHERIDCARDTYPETEXT` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '父亲身份证件类型名称',
  `FTempIDCard` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '个案临时身份证件号',
  `FBasicDisease_CN` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '基础疾病编码',
  `FBasicDisease_Other` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其他基础疾病',
  `FUNIQUEID` varchar(38) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPARITY` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBODYCHECK` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSAFETY` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSAREACODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSAREANAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FEMAIL1` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FEMAIL2` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEDICALRECORD` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FPROOFINFO` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FPPDW` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPPDH` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHECKCODE` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOVEKINDUPDATE` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `FBIRTHDAYD` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSTIME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FISTOP` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPROOFID` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCREATEDEPT` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCREATEUSER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fstatus` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOVEINDATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHASTABU` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOVEKIND` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FEPINO` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCOMMNO` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `USTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUCODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSTIMED` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUTEXT` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCREATECODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMHBEAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBORNKIND` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSCHOOLHIST` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FUSEBYENHANCE` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FGRANTDATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHUKOUGBCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCARDSTATIONNO` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCARDK` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSOCIALSECURITYID` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBORNHOSPITALCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHEALTHID` varchar(23) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FFATHERHOJIPROVINCE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERHOJIPROVINCE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUCODE2` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUCODE3` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHILDUNITID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSMSGATE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERIDCARDEX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSEX` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSMSPREVSENDDATE` datetime DEFAULT NULL,
  `FCHECKOUTREASONCODE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCYBERMAXCARDNO` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCYBERMAXHEALTHNO` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCYBERMAXNATINO` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERHIV` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSMSGATEOPENDATE` datetime DEFAULT NULL,
  `FLONGTIMENOSEE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMULTIPLEBIRTHS` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHECKREASONTEXT` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCLASSONEFINISHED` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FOTHERID_310108` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FOTHERID_310112` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FOTHERID_310115` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FNOTBESPBACTENNAMES` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FQQNO` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTCARDPRINTDATE` datetime DEFAULT NULL,
  `FPROOFGRANTEDCOUNT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIDCARDTYPE` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIDCARDTYPETEXT` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FRESIDENCETYPE31` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FRESIDENCETYPETEXT31` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX1` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX3` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX4` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX5` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX6` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX7` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX8` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX9` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FISAPPBOUND` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否绑定金苗app',
  `FAppBindTime` varchar(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '金苗宝 App 绑定时间',
  `fhealthrecordid` varchar(17) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '城乡居民健康档案编号',
  `fnationalitycode` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '国籍代码',
  `fnationcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '民族代码',
  `fmaritalstatus_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '婚姻状况代码',
  `fcareercode_cn` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '职业类别代码',
  `feducationdegree_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学历代码',
  `fchildunitname` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERMOBILE` varchar(200) DEFAULT NULL,
  `FFATHERMOBILE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fotherguard` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fotherguardrelcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其他监护人与受种者关系代码',
  `ftabucode_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '禁忌证代码',
  `fallergyhist_cn` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '过敏史标志',
  `fdisease_cn` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '既往传染病史代码',
  `freaction_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '既往预防接种异常反应史代码',
  `fupdateusername` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '更新人员',
  `qc_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '迁出标志''1''',
  `fworknaturecode` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '工作性质编码',
  `fcrowdkindcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '人群分类编码',
  `FADULTHBSAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBSAG',
  `FADULTHBSAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBSAB',
  `FAdultHBeAg` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBeAg',
  `FAdultHBeAb` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBeAb',
  `FAdultHBcAb` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBcAb',
  `FBORNHOSPITALCODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '出生医院国标码',
  `FCREATECODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '建档单位编码',
  `FHUKOUCOUNTYCODE_CN` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍县编码',
  `FCREATENAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '建档单位名称',
  `FRESIDECOUNTYCODE_CN` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '居住县国标编码',
  `FCARDSTATIONNO_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '发卡单位国标编码',
  `FCOMMCODE_CN` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '通讯地址编码',
  `FPROOFGRANTSTATIONCODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '条码发放单位国标编码',
  `FRESIDENAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '现住地区名称',
  `FUPDATESTATIONCODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '受种者档案更新单位国标码',
  `FUPDATESTATIONNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '受种者档案更新单位名称',
  `FHUKOUNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍县名称',
  `FVACCINATIONINFOCODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '受种者信息介质识别码',
  `FResideCode_CN` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '现住地区编码',
  `FHuKouCode_CN` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍县编码',
  `FCurrSchoolCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学校机构编码',
  `FCurrSchoolName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学校机构名称',
  `FCurrGradeName` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '年级',
  `FCurrClassName` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '班级',
  `FChronic_Angiocarpy` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-心血管疾病 值域：1（是），0（否）',
  `FChronic_COPD` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-COPD 值域：1（是），0（否）',
  `FChronic_Diabetes` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-糖尿病 值域：1（是），0（否）',
  `FChronic_Hyperten` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-高血压 值域：1（是），0（否）',
  `FChronic_Other` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-其它 值域：1（是），0（否）',
  `FChronic_Tumour` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-肿瘤 值域：1（是），0（否）',
  `FChronic_Without` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-无 值域：1（是），0（否）',
  `FCloudKey` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '“云”端数据键',
  `FCloudSource` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '数据来源',
  `FCommCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '通讯地址编码',
  `FEducationDegree` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学历',
  `FFYZDCode` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '妇幼专档编码',
  `FHealthBoundDateTime` datetime DEFAULT NULL COMMENT '健康卡绑定时间',
  `FHealthBoundDateTimeD` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '健康卡绑定日期，不带时间',
  `FHealthUsed` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否使用过健康卡 值域：1（是），0（否）',
  `FHuKouCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍地址编码',
  `FIllness_Chronic` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其它慢性病描述',
  `FIllness_Family` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '家族病史',
  `FIllness_Shot` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种史',
  `FIsPremature` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否为早产儿（上海：乙肝4针）值域：1（是），0（否）',
  `FIsSmoke` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否吸烟， 值域：1（是），0（否）',
  `FManualCheckOut` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否为手工迁出，值域： 1 - 手工迁出 0/空 - 正常',
  `FMaritalStatus` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '婚姻状况',
  `FProofGrantStationCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '条码发放单位编码',
  `FResideCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '居住地址编码',
  `FSecondMobile` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备用手机',
  `FTabuCode2_CN` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '禁忌症代码2(国标)',
  `FTabuCode3_CN` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '禁忌症代码3(国标)',
  `FMotherWechatID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '母亲微信号',
  `INPUT_VILLAGE_GB` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CURRENT_MANAGEMENT_AREA` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GXSJ` datetime DEFAULT NULL,
  `FLAG` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0' COMMENT '0未更新1已更新',
  PRIMARY KEY (`FCHILDNO`) USING BTREE,
  KEY `epi_childinfo_ind1` (`COUNTYCODE`) USING BTREE,
  KEY `epi_childinfo_STATIONCODE_IDX` (`STATIONCODE`) USING BTREE,
  KEY `epi_childinfo_CID_IDX` (`CID`) USING BTREE,
  KEY `epi_childinfo_IMUNO_IDX` (`IMUNO`) USING BTREE,
  KEY `epi_childinfo_CARDDATE_IDX` (`CARDDATE`) USING BTREE,
  KEY `epi_childinfo_SERVERUPDATETIME_IDX` (`SERVERUPDATETIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_childinfo_cp definition

CREATE TABLE `epi_childinfo_cp` (
  `FCHILDNO` char(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `B001` datetime DEFAULT NULL,
  `B002` datetime DEFAULT NULL,
  `B003` datetime DEFAULT NULL,
  `B004` datetime DEFAULT NULL,
  `B005` datetime DEFAULT NULL,
  `B009` datetime DEFAULT NULL,
  `B010` datetime DEFAULT NULL,
  `B011` datetime DEFAULT NULL,
  `B012` datetime DEFAULT NULL,
  `B013` datetime DEFAULT NULL,
  `B014` datetime DEFAULT NULL,
  `B015` datetime DEFAULT NULL,
  `B016` datetime DEFAULT NULL,
  `B017` datetime DEFAULT NULL,
  `B018` datetime DEFAULT NULL,
  `B019` datetime DEFAULT NULL,
  `B020` datetime DEFAULT NULL,
  `B027` datetime DEFAULT NULL,
  `B028` datetime DEFAULT NULL,
  `B029` datetime DEFAULT NULL,
  `B030` datetime DEFAULT NULL,
  `B031` datetime DEFAULT NULL,
  `B032` datetime DEFAULT NULL,
  `B033` datetime DEFAULT NULL,
  `B034` datetime DEFAULT NULL,
  `B035` datetime DEFAULT NULL,
  `B036` datetime DEFAULT NULL,
  `B037` datetime DEFAULT NULL,
  `B038` datetime DEFAULT NULL,
  `B039` datetime DEFAULT NULL,
  `B040` datetime DEFAULT NULL,
  `B041` datetime DEFAULT NULL,
  `B042` datetime DEFAULT NULL,
  `B043` datetime DEFAULT NULL,
  `B044` datetime DEFAULT NULL,
  `B045` datetime DEFAULT NULL,
  `B046` datetime DEFAULT NULL,
  `B047` datetime DEFAULT NULL,
  `B048` datetime DEFAULT NULL,
  `B049` datetime DEFAULT NULL,
  `B050` datetime DEFAULT NULL,
  `B051` datetime DEFAULT NULL,
  `B052` datetime DEFAULT NULL,
  `B053` datetime DEFAULT NULL,
  `B054` datetime DEFAULT NULL,
  `B055` datetime DEFAULT NULL,
  `B056` datetime DEFAULT NULL,
  `B057` datetime DEFAULT NULL,
  `B058` datetime DEFAULT NULL,
  `B059` datetime DEFAULT NULL,
  `B060` datetime DEFAULT NULL,
  `B061` datetime DEFAULT NULL,
  `B062` datetime DEFAULT NULL,
  `B063` datetime DEFAULT NULL,
  `B064` datetime DEFAULT NULL,
  `B065` datetime DEFAULT NULL,
  `B066` datetime DEFAULT NULL,
  `B067` datetime DEFAULT NULL,
  `B068` datetime DEFAULT NULL,
  `B069` datetime DEFAULT NULL,
  `B070` datetime DEFAULT NULL,
  `B071` datetime DEFAULT NULL,
  `B072` datetime DEFAULT NULL,
  `B073` datetime DEFAULT NULL,
  `B074` datetime DEFAULT NULL,
  `B075` datetime DEFAULT NULL,
  `B076` datetime DEFAULT NULL,
  `B077` datetime DEFAULT NULL,
  `B078` datetime DEFAULT NULL,
  `B079` datetime DEFAULT NULL,
  `B080` datetime DEFAULT NULL,
  `B081` datetime DEFAULT NULL,
  `B082` datetime DEFAULT NULL,
  `B083` datetime DEFAULT NULL,
  `B086` datetime DEFAULT NULL,
  `B088` datetime DEFAULT NULL,
  `B089` datetime DEFAULT NULL,
  `B090` datetime DEFAULT NULL,
  `B091` datetime DEFAULT NULL,
  `B092` datetime DEFAULT NULL,
  `B093` datetime DEFAULT NULL,
  `B094` datetime DEFAULT NULL,
  `B095` datetime DEFAULT NULL,
  `B096` datetime DEFAULT NULL,
  `B097` datetime DEFAULT NULL,
  `B098` datetime DEFAULT NULL,
  `B099` datetime DEFAULT NULL,
  `B100` datetime DEFAULT NULL,
  `B101` datetime DEFAULT NULL,
  `B102` datetime DEFAULT NULL,
  `B103` datetime DEFAULT NULL,
  `B104` datetime DEFAULT NULL,
  `B105` datetime DEFAULT NULL,
  `B106` datetime DEFAULT NULL,
  `B107` datetime DEFAULT NULL,
  `B108` datetime DEFAULT NULL,
  `B109` datetime DEFAULT NULL,
  `B110` datetime DEFAULT NULL,
  `B111` datetime DEFAULT NULL,
  `B112` datetime DEFAULT NULL,
  `B113` datetime DEFAULT NULL,
  `B114` datetime DEFAULT NULL,
  `B115` datetime DEFAULT NULL,
  `B116` datetime DEFAULT NULL,
  `B117` datetime DEFAULT NULL,
  `B118` datetime DEFAULT NULL,
  `B119` datetime DEFAULT NULL,
  `B120` datetime DEFAULT NULL,
  `B121` datetime DEFAULT NULL,
  `B122` datetime DEFAULT NULL,
  `B123` datetime DEFAULT NULL,
  `B124` datetime DEFAULT NULL,
  `B127` datetime DEFAULT NULL,
  `B128` datetime DEFAULT NULL,
  `B130` datetime DEFAULT NULL,
  `B131` datetime DEFAULT NULL,
  `B132` datetime DEFAULT NULL,
  `B133` datetime DEFAULT NULL,
  `B134` datetime DEFAULT NULL,
  `B135` datetime DEFAULT NULL,
  `B136` datetime DEFAULT NULL,
  `B137` datetime DEFAULT NULL,
  `B138` datetime DEFAULT NULL,
  `B139` datetime DEFAULT NULL,
  `B140` datetime DEFAULT NULL,
  `B141` datetime DEFAULT NULL,
  `B142` datetime DEFAULT NULL,
  `B143` datetime DEFAULT NULL,
  `B144` datetime DEFAULT NULL,
  `B145` datetime DEFAULT NULL,
  `B146` datetime DEFAULT NULL,
  `B147` datetime DEFAULT NULL,
  `B148` datetime DEFAULT NULL,
  `B155` datetime DEFAULT NULL,
  `B156` datetime DEFAULT NULL,
  `B157` datetime DEFAULT NULL,
  `B158` datetime DEFAULT NULL,
  `B159` datetime DEFAULT NULL,
  `B160` datetime DEFAULT NULL,
  `B161` datetime DEFAULT NULL,
  `B162` datetime DEFAULT NULL,
  `B163` datetime DEFAULT NULL,
  `B164` datetime DEFAULT NULL,
  `B165` datetime DEFAULT NULL,
  `B166` datetime DEFAULT NULL,
  `B167` datetime DEFAULT NULL,
  `B168` datetime DEFAULT NULL,
  `B169` datetime DEFAULT NULL,
  `B170` datetime DEFAULT NULL,
  `B171` datetime DEFAULT NULL,
  `B172` datetime DEFAULT NULL,
  `B173` datetime DEFAULT NULL,
  `B174` datetime DEFAULT NULL,
  `B175` datetime DEFAULT NULL,
  `B176` datetime DEFAULT NULL,
  `B177` datetime DEFAULT NULL,
  `B178` datetime DEFAULT NULL,
  `B179` datetime DEFAULT NULL,
  `B180` datetime DEFAULT NULL,
  `B181` datetime DEFAULT NULL,
  `B182` datetime DEFAULT NULL,
  `B304` datetime DEFAULT NULL,
  `B305` datetime DEFAULT NULL,
  `B306` datetime DEFAULT NULL,
  `B307` datetime DEFAULT NULL,
  `B308` datetime DEFAULT NULL,
  `B309` datetime DEFAULT NULL,
  `B310` datetime DEFAULT NULL,
  `B311` datetime DEFAULT NULL,
  `B312` datetime DEFAULT NULL,
  `B313` datetime DEFAULT NULL,
  `B317` datetime DEFAULT NULL,
  `B318` datetime DEFAULT NULL,
  `B319` datetime DEFAULT NULL,
  `B320` datetime DEFAULT NULL,
  `B321` datetime DEFAULT NULL,
  `B322` datetime DEFAULT NULL,
  `B323` datetime DEFAULT NULL,
  `B324` datetime DEFAULT NULL,
  `B325` datetime DEFAULT NULL,
  `B326` datetime DEFAULT NULL,
  `B327` datetime DEFAULT NULL,
  `B328` datetime DEFAULT NULL,
  `B329` datetime DEFAULT NULL,
  `B330` datetime DEFAULT NULL,
  `B331` datetime DEFAULT NULL,
  `B332` datetime DEFAULT NULL,
  `B333` datetime DEFAULT NULL,
  `B334` datetime DEFAULT NULL,
  `B335` datetime DEFAULT NULL,
  `B336` datetime DEFAULT NULL,
  `B337` datetime DEFAULT NULL,
  `B338` datetime DEFAULT NULL,
  `B339` datetime DEFAULT NULL,
  `B340` datetime DEFAULT NULL,
  `B343` datetime DEFAULT NULL,
  `B344` datetime DEFAULT NULL,
  `B345` datetime DEFAULT NULL,
  `B346` datetime DEFAULT NULL,
  `B347` datetime DEFAULT NULL,
  `B348` datetime DEFAULT NULL,
  `B349` datetime DEFAULT NULL,
  `B350` datetime DEFAULT NULL,
  `B351` datetime DEFAULT NULL,
  `B352` datetime DEFAULT NULL,
  `B353` datetime DEFAULT NULL,
  `B354` datetime DEFAULT NULL,
  `B355` datetime DEFAULT NULL,
  `B356` datetime DEFAULT NULL,
  `B357` datetime DEFAULT NULL,
  `B358` datetime DEFAULT NULL,
  `B359` datetime DEFAULT NULL,
  `B360` datetime DEFAULT NULL,
  `B361` datetime DEFAULT NULL,
  `B362` datetime DEFAULT NULL,
  `B363` datetime DEFAULT NULL,
  `B364` datetime DEFAULT NULL,
  `B365` datetime DEFAULT NULL,
  `B366` datetime DEFAULT NULL,
  `B367` datetime DEFAULT NULL,
  `B368` datetime DEFAULT NULL,
  `B369` datetime DEFAULT NULL,
  `B370` datetime DEFAULT NULL,
  `B371` datetime DEFAULT NULL,
  `B372` datetime DEFAULT NULL,
  `B373` datetime DEFAULT NULL,
  `B374` datetime DEFAULT NULL,
  `B375` datetime DEFAULT NULL,
  `B376` datetime DEFAULT NULL,
  `B377` datetime DEFAULT NULL,
  `B378` datetime DEFAULT NULL,
  `B379` datetime DEFAULT NULL,
  `B380` datetime DEFAULT NULL,
  `B381` datetime DEFAULT NULL,
  `B382` datetime DEFAULT NULL,
  `B383` datetime DEFAULT NULL,
  `B384` datetime DEFAULT NULL,
  `B385` datetime DEFAULT NULL,
  `B386` datetime DEFAULT NULL,
  `B387` datetime DEFAULT NULL,
  `B388` datetime DEFAULT NULL,
  `B391` datetime DEFAULT NULL,
  `B392` datetime DEFAULT NULL,
  `B393` datetime DEFAULT NULL,
  `B394` datetime DEFAULT NULL,
  `B401` datetime DEFAULT NULL,
  `B402` datetime DEFAULT NULL,
  `B403` datetime DEFAULT NULL,
  `B404` datetime DEFAULT NULL,
  `B405` datetime DEFAULT NULL,
  `B406` datetime DEFAULT NULL,
  `B407` datetime DEFAULT NULL,
  `B408` datetime DEFAULT NULL,
  `B409` datetime DEFAULT NULL,
  `B410` datetime DEFAULT NULL,
  `B411` datetime DEFAULT NULL,
  `B412` datetime DEFAULT NULL,
  `B413` datetime DEFAULT NULL,
  `B414` datetime DEFAULT NULL,
  `B415` datetime DEFAULT NULL,
  `B416` datetime DEFAULT NULL,
  `B417` datetime DEFAULT NULL,
  `B418` datetime DEFAULT NULL,
  `B419` datetime DEFAULT NULL,
  `B420` datetime DEFAULT NULL,
  `B421` datetime DEFAULT NULL,
  `B422` datetime DEFAULT NULL,
  `B423` datetime DEFAULT NULL,
  `B424` datetime DEFAULT NULL,
  `B425` datetime DEFAULT NULL,
  `B426` datetime DEFAULT NULL,
  `B427` datetime DEFAULT NULL,
  `B428` datetime DEFAULT NULL,
  `B429` datetime DEFAULT NULL,
  `B430` datetime DEFAULT NULL,
  `B431` datetime DEFAULT NULL,
  `B432` datetime DEFAULT NULL,
  `B434` datetime DEFAULT NULL,
  `B435` datetime DEFAULT NULL,
  `B436` datetime DEFAULT NULL,
  `B437` datetime DEFAULT NULL,
  `B438` datetime DEFAULT NULL,
  `B439` datetime DEFAULT NULL,
  `B440` datetime DEFAULT NULL,
  `B441` datetime DEFAULT NULL,
  `B442` datetime DEFAULT NULL,
  `B443` datetime DEFAULT NULL,
  `B444` datetime DEFAULT NULL,
  `B445` datetime DEFAULT NULL,
  `B446` datetime DEFAULT NULL,
  `B447` datetime DEFAULT NULL,
  `B448` datetime DEFAULT NULL,
  `B449` datetime DEFAULT NULL,
  `B450` datetime DEFAULT NULL,
  `B451` datetime DEFAULT NULL,
  `B452` datetime DEFAULT NULL,
  `B453` datetime DEFAULT NULL,
  `B454` datetime DEFAULT NULL,
  `B455` datetime DEFAULT NULL,
  `B456` datetime DEFAULT NULL,
  `B457` datetime DEFAULT NULL,
  `B458` datetime DEFAULT NULL,
  `B459` datetime DEFAULT NULL,
  `B460` datetime DEFAULT NULL,
  `B461` datetime DEFAULT NULL,
  `B462` datetime DEFAULT NULL,
  `B463` datetime DEFAULT NULL,
  `B464` datetime DEFAULT NULL,
  `B465` datetime DEFAULT NULL,
  `B466` datetime DEFAULT NULL,
  `B467` datetime DEFAULT NULL,
  `B468` datetime DEFAULT NULL,
  `B469` datetime DEFAULT NULL,
  `B470` datetime DEFAULT NULL,
  `B471` datetime DEFAULT NULL,
  `B472` datetime DEFAULT NULL,
  `B473` datetime DEFAULT NULL,
  `B474` datetime DEFAULT NULL,
  `B475` datetime DEFAULT NULL,
  `B476` datetime DEFAULT NULL,
  `B477` datetime DEFAULT NULL,
  `B478` datetime DEFAULT NULL,
  `B479` datetime DEFAULT NULL,
  `B480` datetime DEFAULT NULL,
  `B481` datetime DEFAULT NULL,
  `B482` datetime DEFAULT NULL,
  `B483` datetime DEFAULT NULL,
  `B484` datetime DEFAULT NULL,
  `B485` datetime DEFAULT NULL,
  `B486` datetime DEFAULT NULL,
  `B487` datetime DEFAULT NULL,
  `B488` datetime DEFAULT NULL,
  `B489` datetime DEFAULT NULL,
  `B490` datetime DEFAULT NULL,
  `B491` datetime DEFAULT NULL,
  `B492` datetime DEFAULT NULL,
  `B493` datetime DEFAULT NULL,
  `B494` datetime DEFAULT NULL,
  `B495` datetime DEFAULT NULL,
  `B496` datetime DEFAULT NULL,
  `B497` datetime DEFAULT NULL,
  `B498` datetime DEFAULT NULL,
  `B499` datetime DEFAULT NULL,
  `B500` datetime DEFAULT NULL,
  `B501` datetime DEFAULT NULL,
  `B502` datetime DEFAULT NULL,
  `B503` datetime DEFAULT NULL,
  `B504` datetime DEFAULT NULL,
  `B505` datetime DEFAULT NULL,
  `B506` datetime DEFAULT NULL,
  `B507` datetime DEFAULT NULL,
  `B508` datetime DEFAULT NULL,
  `B509` datetime DEFAULT NULL,
  `B510` datetime DEFAULT NULL,
  `B511` datetime DEFAULT NULL,
  `B512` datetime DEFAULT NULL,
  `B513` datetime DEFAULT NULL,
  `B514` datetime DEFAULT NULL,
  `B515` datetime DEFAULT NULL,
  `B516` datetime DEFAULT NULL,
  `B517` datetime DEFAULT NULL,
  `B518` datetime DEFAULT NULL,
  `B519` datetime DEFAULT NULL,
  `B520` datetime DEFAULT NULL,
  `B521` datetime DEFAULT NULL,
  `B522` datetime DEFAULT NULL,
  `B523` datetime DEFAULT NULL,
  `B524` datetime DEFAULT NULL,
  `B525` datetime DEFAULT NULL,
  `B526` datetime DEFAULT NULL,
  `B527` datetime DEFAULT NULL,
  `B528` datetime DEFAULT NULL,
  `B529` datetime DEFAULT NULL,
  `B530` datetime DEFAULT NULL,
  `B531` datetime DEFAULT NULL,
  `B532` datetime DEFAULT NULL,
  `B533` datetime DEFAULT NULL,
  `B534` datetime DEFAULT NULL,
  `B535` datetime DEFAULT NULL,
  `B536` datetime DEFAULT NULL,
  `B537` datetime DEFAULT NULL,
  `B538` datetime DEFAULT NULL,
  `B539` datetime DEFAULT NULL,
  `B540` datetime DEFAULT NULL,
  `B541` datetime DEFAULT NULL,
  `B542` datetime DEFAULT NULL,
  `B543` datetime DEFAULT NULL,
  `B544` datetime DEFAULT NULL,
  `B545` datetime DEFAULT NULL,
  `B546` datetime DEFAULT NULL,
  `B547` datetime DEFAULT NULL,
  `B548` datetime DEFAULT NULL,
  `B549` datetime DEFAULT NULL,
  `B550` datetime DEFAULT NULL,
  `B551` datetime DEFAULT NULL,
  `B552` datetime DEFAULT NULL,
  `B553` datetime DEFAULT NULL,
  `B554` datetime DEFAULT NULL,
  `B555` datetime DEFAULT NULL,
  `B556` datetime DEFAULT NULL,
  `B557` datetime DEFAULT NULL,
  `B558` datetime DEFAULT NULL,
  `B559` datetime DEFAULT NULL,
  `B560` datetime DEFAULT NULL,
  `B561` datetime DEFAULT NULL,
  `B562` datetime DEFAULT NULL,
  `B563` datetime DEFAULT NULL,
  `B564` datetime DEFAULT NULL,
  `B565` datetime DEFAULT NULL,
  `B566` datetime DEFAULT NULL,
  `B567` datetime DEFAULT NULL,
  `B568` datetime DEFAULT NULL,
  `B569` datetime DEFAULT NULL,
  `B570` datetime DEFAULT NULL,
  `B571` datetime DEFAULT NULL,
  `B572` datetime DEFAULT NULL,
  `B573` datetime DEFAULT NULL,
  `B574` datetime DEFAULT NULL,
  `B575` datetime DEFAULT NULL,
  `B576` datetime DEFAULT NULL,
  `B577` datetime DEFAULT NULL,
  `B578` datetime DEFAULT NULL,
  `B579` datetime DEFAULT NULL,
  `B580` datetime DEFAULT NULL,
  `B581` datetime DEFAULT NULL,
  `B582` datetime DEFAULT NULL,
  `B583` datetime DEFAULT NULL,
  `B584` datetime DEFAULT NULL,
  `B585` datetime DEFAULT NULL,
  `B586` datetime DEFAULT NULL,
  `B587` datetime DEFAULT NULL,
  `B588` datetime DEFAULT NULL,
  `B589` datetime DEFAULT NULL,
  `B590` datetime DEFAULT NULL,
  `B591` datetime DEFAULT NULL,
  `B592` datetime DEFAULT NULL,
  `B593` datetime DEFAULT NULL,
  `B594` datetime DEFAULT NULL,
  `B595` datetime DEFAULT NULL,
  `B596` datetime DEFAULT NULL,
  `B597` datetime DEFAULT NULL,
  `B598` datetime DEFAULT NULL,
  `B599` datetime DEFAULT NULL,
  `B600` datetime DEFAULT NULL,
  `B601` datetime DEFAULT NULL,
  `B602` datetime DEFAULT NULL,
  `B603` datetime DEFAULT NULL,
  `B604` datetime DEFAULT NULL,
  `B605` datetime DEFAULT NULL,
  `B606` datetime DEFAULT NULL,
  `B607` datetime DEFAULT NULL,
  `B608` datetime DEFAULT NULL,
  `B609` datetime DEFAULT NULL,
  `B610` datetime DEFAULT NULL,
  `B611` datetime DEFAULT NULL,
  `B612` datetime DEFAULT NULL,
  `B613` datetime DEFAULT NULL,
  `B614` datetime DEFAULT NULL,
  `B615` datetime DEFAULT NULL,
  `B616` datetime DEFAULT NULL,
  `B617` datetime DEFAULT NULL,
  `B618` datetime DEFAULT NULL,
  `B619` datetime DEFAULT NULL,
  `B620` datetime DEFAULT NULL,
  `B621` datetime DEFAULT NULL,
  `B622` datetime DEFAULT NULL,
  `B623` datetime DEFAULT NULL,
  `B624` datetime DEFAULT NULL,
  `B625` datetime DEFAULT NULL,
  `B626` datetime DEFAULT NULL,
  `B627` datetime DEFAULT NULL,
  `B628` datetime DEFAULT NULL,
  `B629` datetime DEFAULT NULL,
  `B630` datetime DEFAULT NULL,
  `B631` datetime DEFAULT NULL,
  `B632` datetime DEFAULT NULL,
  `B633` datetime DEFAULT NULL,
  `B634` datetime DEFAULT NULL,
  `B635` datetime DEFAULT NULL,
  `B636` datetime DEFAULT NULL,
  `B637` datetime DEFAULT NULL,
  `B638` datetime DEFAULT NULL,
  `B639` datetime DEFAULT NULL,
  `B640` datetime DEFAULT NULL,
  `B641` datetime DEFAULT NULL,
  `B642` datetime DEFAULT NULL,
  `B643` datetime DEFAULT NULL,
  `B644` datetime DEFAULT NULL,
  `B645` datetime DEFAULT NULL,
  `B646` datetime DEFAULT NULL,
  `B647` datetime DEFAULT NULL,
  `B648` datetime DEFAULT NULL,
  `B649` datetime DEFAULT NULL,
  `B650` datetime DEFAULT NULL,
  `B651` datetime DEFAULT NULL,
  `B652` datetime DEFAULT NULL,
  `B653` datetime DEFAULT NULL,
  `B654` datetime DEFAULT NULL,
  `B655` datetime DEFAULT NULL,
  `B656` datetime DEFAULT NULL,
  `B657` datetime DEFAULT NULL,
  `B658` datetime DEFAULT NULL,
  `B659` datetime DEFAULT NULL,
  `B660` datetime DEFAULT NULL,
  `B661` datetime DEFAULT NULL,
  `B662` datetime DEFAULT NULL,
  `B663` datetime DEFAULT NULL,
  `B664` datetime DEFAULT NULL,
  `B665` datetime DEFAULT NULL,
  `B666` datetime DEFAULT NULL,
  `B667` datetime DEFAULT NULL,
  `B668` datetime DEFAULT NULL,
  `B669` datetime DEFAULT NULL,
  `B670` datetime DEFAULT NULL,
  `B671` datetime DEFAULT NULL,
  `B672` datetime DEFAULT NULL,
  `B673` datetime DEFAULT NULL,
  `B674` datetime DEFAULT NULL,
  `B675` datetime DEFAULT NULL,
  `B676` datetime DEFAULT NULL,
  `B677` datetime DEFAULT NULL,
  `B678` datetime DEFAULT NULL,
  `B679` datetime DEFAULT NULL,
  `B680` datetime DEFAULT NULL,
  `B681` datetime DEFAULT NULL,
  `B682` datetime DEFAULT NULL,
  `B683` datetime DEFAULT NULL,
  `B684` datetime DEFAULT NULL,
  `B685` datetime DEFAULT NULL,
  `B686` datetime DEFAULT NULL,
  `B687` datetime DEFAULT NULL,
  `B688` datetime DEFAULT NULL,
  `B689` datetime DEFAULT NULL,
  `B690` datetime DEFAULT NULL,
  `B691` datetime DEFAULT NULL,
  `B692` datetime DEFAULT NULL,
  `B693` datetime DEFAULT NULL,
  `B694` datetime DEFAULT NULL,
  `B695` datetime DEFAULT NULL,
  `B696` datetime DEFAULT NULL,
  `B697` datetime DEFAULT NULL,
  `B698` datetime DEFAULT NULL,
  `B699` datetime DEFAULT NULL,
  `B700` datetime DEFAULT NULL,
  `B701` datetime DEFAULT NULL,
  `B702` datetime DEFAULT NULL,
  `B703` datetime DEFAULT NULL,
  PRIMARY KEY (`FCHILDNO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_childinfo_del definition

CREATE TABLE `epi_childinfo_del` (
  `FCHILDNO` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SERVERUPDATETIME` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_childinfo_eliminate definition

CREATE TABLE `epi_childinfo_eliminate` (
  `DELTIME` datetime NOT NULL,
  `UNITCODE` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UNITNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SUPCODE` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CHILDNO` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `IMUNO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PWD` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `NAME` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTH` datetime DEFAULT NULL,
  `SEX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BLOODTYPE` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REGTYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DWELLADDR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `COMADDR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FATHERNAME` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOTHERNAME` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FATHERUNIT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOTHERUNIT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOBPHONE` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `OTHERPHONE` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTHHOS` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTHDR` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CARDUNITCODE` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CARDDATE` datetime DEFAULT NULL,
  `BOOKINGDATE` datetime DEFAULT NULL,
  `CARDSUMNO` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `INSMONEY` decimal(6,2) DEFAULT NULL,
  `MHBSAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHBSAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBEAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BCGSCAR` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ALLERGY` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TABU` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SMSTAG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `PHONETAG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TRANSCOUNT` decimal(3,0) DEFAULT '0',
  `TRANSTIME` datetime DEFAULT NULL,
  `remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UPDATETIME` datetime DEFAULT NULL,
  `REGADDR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JWH` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SFJJ` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `QHJZ` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CBANK` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `INSP` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CSTATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CUPDATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TABUBACT` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `COUNTYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `QCJZ` datetime DEFAULT NULL,
  `BASECODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FATHERID` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MOTHERID` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CID` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `STATIONCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CITYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `WEIGHT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBSAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBCAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MHBEAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTHNO` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHILDNO` char(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FIMMUBILL` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIMMUGRANTDATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIMMUGRANTSTATIONCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIMMUGRANTSTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JOB_ID` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SERVERUPDATETIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `FPROOFGRANTDATE` datetime DEFAULT NULL,
  `FOUTOFPROVINCE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `STATUSTIME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIsAdult` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否为成人  1(是)，0(否)',
  `FChildFromCard` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '儿童基本信息是否来自于IC卡  1(是)，0(否)',
  `FGestationalWeeks` decimal(5,1) DEFAULT NULL,
  `FNETHEALTHID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '电子健康卡唯一标识',
  `FMOTHERIDCARDTYPE` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '母亲身份证件类型',
  `FMOTHERIDCARDTYPETEXT` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '母亲身份证件类型名称',
  `FFATHERIDCARDTYPE` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '父亲身份证件类型',
  `FFATHERIDCARDTYPETEXT` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '父亲身份证件类型名称',
  `FTempIDCard` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '个案临时身份证件号',
  `FBasicDisease_CN` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '基础疾病编码',
  `FBasicDisease_Other` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其他基础疾病',
  `FUNIQUEID` varchar(38) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPARITY` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBODYCHECK` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSAFETY` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSAREACODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSAREANAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FEMAIL1` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FEMAIL2` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEDICALRECORD` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FPROOFINFO` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FPPDW` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPPDH` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHECKCODE` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOVEKINDUPDATE` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  `FBIRTHDAYD` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSTIME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FISTOP` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPROOFID` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCREATEDEPT` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCREATEUSER` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fstatus` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOVEINDATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHASTABU` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOVEKIND` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FEPINO` char(14) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCOMMNO` char(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `USTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUCODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSTIMED` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUTEXT` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCREATECODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMHBEAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBORNKIND` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSCHOOLHIST` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FUSEBYENHANCE` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FGRANTDATE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHUKOUGBCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCARDSTATIONNO` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCARDK` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSOCIALSECURITYID` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBORNHOSPITALCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FHEALTHID` varchar(23) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FFATHERHOJIPROVINCE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERHOJIPROVINCE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUCODE2` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FTABUCODE3` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHILDUNITID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSMSGATE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERIDCARDEX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATUSEX` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSMSPREVSENDDATE` datetime DEFAULT NULL,
  `FCHECKOUTREASONCODE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCYBERMAXCARDNO` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCYBERMAXHEALTHNO` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCYBERMAXNATINO` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERHIV` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSMSGATEOPENDATE` datetime DEFAULT NULL,
  `FLONGTIMENOSEE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMULTIPLEBIRTHS` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCHECKREASONTEXT` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FCLASSONEFINISHED` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FOTHERID_310108` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FOTHERID_310112` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FOTHERID_310115` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FNOTBESPBACTENNAMES` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `FQQNO` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTCARDPRINTDATE` datetime DEFAULT NULL,
  `FPROOFGRANTEDCOUNT` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIDCARDTYPE` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FIDCARDTYPETEXT` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FRESIDENCETYPE31` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FRESIDENCETYPETEXT31` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX1` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX3` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX4` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX5` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX6` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX7` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX8` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMEMOEX9` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FISAPPBOUND` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否绑定金苗app',
  `FAppBindTime` varchar(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '金苗宝 App 绑定时间',
  `fhealthrecordid` varchar(17) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '城乡居民健康档案编号',
  `fnationalitycode` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '国籍代码',
  `fnationcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '民族代码',
  `fmaritalstatus_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '婚姻状况代码',
  `fcareercode_cn` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '职业类别代码',
  `feducationdegree_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学历代码',
  `fchildunitname` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FMOTHERMOBILE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FFATHERMOBILE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fotherguard` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fotherguardrelcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其他监护人与受种者关系代码',
  `ftabucode_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '禁忌证代码',
  `fallergyhist_cn` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '过敏史标志',
  `fdisease_cn` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '既往传染病史代码',
  `freaction_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '既往预防接种异常反应史代码',
  `fupdateusername` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '更新人员',
  `qc_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '迁出标志''1''',
  `fworknaturecode` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '工作性质编码',
  `fcrowdkindcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '人群分类编码',
  `FADULTHBSAG` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBSAG',
  `FADULTHBSAB` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBSAB',
  `FAdultHBeAg` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBeAg',
  `FAdultHBeAb` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBeAb',
  `FAdultHBcAb` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '成人HBcAb',
  `FBORNHOSPITALCODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '出生医院国标码',
  `FCREATECODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '建档单位编码',
  `FHUKOUCOUNTYCODE_CN` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍县编码',
  `FCREATENAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '建档单位名称',
  `FRESIDECOUNTYCODE_CN` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '居住县国标编码',
  `FCARDSTATIONNO_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '发卡单位国标编码',
  `FCOMMCODE_CN` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '通讯地址编码',
  `FPROOFGRANTSTATIONCODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '条码发放单位国标编码',
  `FRESIDENAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '现住地区名称',
  `FUPDATESTATIONCODE_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '受种者档案更新单位国标码',
  `FUPDATESTATIONNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '受种者档案更新单位名称',
  `FHUKOUNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍县名称',
  `FVACCINATIONINFOCODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '受种者信息介质识别码',
  `FResideCode_CN` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '现住地区编码',
  `FHuKouCode_CN` varchar(9) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍县编码',
  `FCurrSchoolCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学校机构编码',
  `FCurrSchoolName` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学校机构名称',
  `FCurrGradeName` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '年级',
  `FCurrClassName` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '班级',
  `FChronic_Angiocarpy` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-心血管疾病 值域：1（是），0（否）',
  `FChronic_COPD` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-COPD 值域：1（是），0（否）',
  `FChronic_Diabetes` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-糖尿病 值域：1（是），0（否）',
  `FChronic_Hyperten` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-高血压 值域：1（是），0（否）',
  `FChronic_Other` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-其它 值域：1（是），0（否）',
  `FChronic_Tumour` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-肿瘤 值域：1（是），0（否）',
  `FChronic_Without` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否慢性病史-无 值域：1（是），0（否）',
  `FCloudKey` varchar(24) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '“云”端数据键',
  `FCloudSource` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '数据来源',
  `FCommCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '通讯地址编码',
  `FEducationDegree` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '学历',
  `FFYZDCode` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '妇幼专档编码',
  `FHealthBoundDateTime` datetime DEFAULT NULL COMMENT '健康卡绑定时间',
  `FHealthBoundDateTimeD` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '健康卡绑定日期，不带时间',
  `FHealthUsed` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否使用过健康卡 值域：1（是），0（否）',
  `FHuKouCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '户籍地址编码',
  `FIllness_Chronic` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '其它慢性病描述',
  `FIllness_Family` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '家族病史',
  `FIllness_Shot` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种史',
  `FIsPremature` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否为早产儿（上海：乙肝4针）值域：1（是），0（否）',
  `FIsSmoke` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否吸烟， 值域：1（是），0（否）',
  `FManualCheckOut` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '是否为手工迁出，值域： 1 - 手工迁出 0/空 - 正常',
  `FMaritalStatus` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '婚姻状况',
  `FProofGrantStationCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '条码发放单位编码',
  `FResideCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '居住地址编码',
  `FSecondMobile` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '备用手机',
  `FTabuCode2_CN` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '禁忌症代码2(国标)',
  `FTabuCode3_CN` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '禁忌症代码3(国标)',
  `FMotherWechatID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '母亲微信号',
  `INPUT_VILLAGE_GB` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CURRENT_MANAGEMENT_AREA` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GXSJ` datetime DEFAULT NULL,
  `FLAG` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  KEY `epi_childinfo_eliminate_1` (`DELTIME`) USING BTREE,
  KEY `epi_childinfo_eliminate_2` (`FCHILDNO`) USING BTREE,
  KEY `epi_childinfo_eliminate_STATIONCODE_IDX` (`STATIONCODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_jzjl definition

CREATE TABLE `epi_jzjl` (
  `JZRQ` datetime DEFAULT NULL,
  `YMPH` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZYS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `YMJG` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REASON` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CANCELDATE` datetime DEFAULT NULL,
  `FCHILDNO` char(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FSHOTKIND` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '1',
  `FENTERPNO` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTDATED` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FREACTIONCODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPLACECODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUNDODATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUNDODATED` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPRODUCTNO` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `USTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBACTID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FSOURCE` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBATCHKEY` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUSEIMMUBILL` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPRODUCTLISTCODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FLASTEDITDATETIME` datetime DEFAULT NULL,
  `FINPUTDATE` datetime DEFAULT NULL,
  `FMONITORCODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FFREECHARGE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UISOUT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FWAITMINUTES` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SERVERUPDATETIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `FSHOTWAYCODE` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTMEMO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTSPEC` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSAMENESSFROM` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FShotFromCard` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '儿童本条接种记录是否来自于IC卡  1(是)，0(否)',
  `FBatchExpiryDate` date DEFAULT NULL,
  `fpropertycode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '疫苗属性代码：新冠06,国家免规01,强化05,应急03,其他非免规04,自动赋值暂无02',
  `fbactpaymode_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付方式',
  `FOPERATESTATIONCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊编码',
  `FOPERATESTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊名称',
  `FVACCTYPECODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUpdateStationCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修改单位编码',
  `FStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种单位国标码',
  `FOperateStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊国标码（录入单位编码）',
  `FUpdateStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修改单位国标码',
  `FInputDateTime` datetime DEFAULT NULL COMMENT '录入时间',
  `FUpdateDateTime` datetime DEFAULT NULL COMMENT '修改时间',
  `FUpdateStationName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '更新接种门诊名称',
  `FShotGuid` varchar(42) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种记录唯一ID(6位县区行政区划代码+GUID)',
  `VACCINATION` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VACCINATION_TIME` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VACCINATION_COUNTY_GB` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UPLOAD_DATE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TABU_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GXSJ` datetime DEFAULT NULL,
  PRIMARY KEY (`FCHILDNO`,`FBACTID`) USING BTREE,
  UNIQUE KEY `epi_jzjl_2` (`FShotGuid`) USING BTREE,
  KEY `epi_jzjl_1` (`FMONITORCODE`) USING BTREE,
  KEY `epi_jzjl_FStationCode_CN_IDX` (`FStationCode_CN`) USING BTREE,
  KEY `epi_jzjl_JZRQ_IDX` (`JZRQ`) USING BTREE,
  KEY `epi_jzjl_SERVERUPDATETIME_IDX` (`SERVERUPDATETIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_jzjl_eliminate definition

CREATE TABLE `epi_jzjl_eliminate` (
  `DELTIME` datetime NOT NULL,
  `JZRQ` datetime DEFAULT NULL,
  `YMPH` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZYS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `YMJG` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REASON` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CANCELDATE` datetime DEFAULT NULL,
  `FCHILDNO` char(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FSHOTKIND` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '1',
  `FENTERPNO` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTDATED` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FREACTIONCODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPLACECODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUNDODATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUNDODATED` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPRODUCTNO` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `USTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBACTID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FSOURCE` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBATCHKEY` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUSEIMMUBILL` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPRODUCTLISTCODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FLASTEDITDATETIME` datetime DEFAULT NULL,
  `FINPUTDATE` datetime DEFAULT NULL,
  `FMONITORCODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FFREECHARGE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UISOUT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FWAITMINUTES` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SERVERUPDATETIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `FSHOTWAYCODE` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTMEMO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTSPEC` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSAMENESSFROM` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FShotFromCard` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '儿童本条接种记录是否来自于IC卡  1(是)，0(否)',
  `FBatchExpiryDate` date DEFAULT NULL,
  `fpropertycode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '疫苗属性代码：新冠06,国家免规01,强化05,应急03,其他非免规04,自动赋值暂无02',
  `fbactpaymode_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付方式',
  `FOPERATESTATIONCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊编码',
  `FOPERATESTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊名称',
  `FVACCTYPECODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUpdateStationCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修改单位编码',
  `FStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种单位国标码',
  `FOperateStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊国标码（录入单位编码）',
  `FUpdateStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修改单位国标码',
  `FInputDateTime` datetime DEFAULT NULL COMMENT '录入时间',
  `FUpdateDateTime` datetime DEFAULT NULL COMMENT '修改时间',
  `FUpdateStationName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '更新接种门诊名称',
  `FShotGuid` varchar(42) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种记录唯一ID(6位县区行政区划代码+GUID)',
  `VACCINATION` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VACCINATION_TIME` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VACCINATION_COUNTY_GB` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UPLOAD_DATE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TABU_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GXSJ` datetime DEFAULT NULL,
  `UNDOREASON` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '撤销原因',
  `UNDO_UNITID` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '撤销门诊编码',
  `FLAG` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  KEY `epi_jzjl_eliminate_2` (`FCHILDNO`,`FBACTID`) USING BTREE,
  KEY `epi_jzjl_eliminate_1` (`DELTIME`) USING BTREE,
  KEY `epi_jzjl_eliminate_FShotGuid_IDX` (`FShotGuid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_write_error_log definition

CREATE TABLE `epi_write_error_log` (
  `DATA_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DATA_INFO` varchar(5000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '个案：YFJZ_GRJBXX_NINGBO 接种信息：YFJZ_JZXX_NINGBO  ',
  `DATA_ERROR` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  KEY `type_index` (`DATA_TYPE`) USING BTREE,
  KEY `time_index` (`CREATE_TIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_write_log definition

CREATE TABLE `epi_write_log` (
  `DATA_TYPE` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SUCCESS_NUM` bigint DEFAULT NULL,
  `ERROR_NUM` bigint DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  KEY `type_index` (`DATA_TYPE`) USING BTREE,
  KEY `time_index` (`CREATE_TIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_xg_info definition

CREATE TABLE `epi_xg_info` (
  `FCHILDNO` varchar(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '受种者编码',
  `CITYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `COUNTYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SUPCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `STATIONCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTH` datetime DEFAULT NULL COMMENT '出生日期',
  `NAME` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CID` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '身份证件号码',
  `STATUS` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '在册状态',
  `MOBPHONE` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '移动电话',
  `OTHERPHONE` varchar(72) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '固定电话',
  `FCHILDUNITNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DWELLADDR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTDATED_1` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第1剂次接种日期',
  `STATIONCODE_1` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第1剂次接种单位编码',
  `SUPCODE_1` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第1剂次接种街道编码',
  `COUNTYCODE_1` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第1剂次接种区县编码',
  `CITYCODE_1` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第1剂次接种地市编码',
  `FENTERPNO_1` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第1剂次生产厂家编码',
  `FPRODUCTNO_1` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第1剂次疫苗制品',
  `FSTATIONNAME_1` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTDATED_2` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第2剂次接种日期',
  `STATIONCODE_2` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第2剂次接种单位编码',
  `SUPCODE_2` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第2剂次接种街道编码',
  `COUNTYCODE_2` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第2剂次接种区县编码',
  `CITYCODE_2` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第2剂次接种地市编码',
  `FENTERPNO_2` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第2剂次生产厂家编码',
  `FPRODUCTNO_2` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第2剂次疫苗制品',
  `FSTATIONNAME_2` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTDATED_3` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第3剂次接种日期',
  `STATIONCODE_3` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第3剂次接种单位编码',
  `SUPCODE_3` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第3剂次接种街道编码',
  `COUNTYCODE_3` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第3剂次接种区县编码',
  `CITYCODE_3` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第3剂次接种地市编码',
  `FENTERPNO_3` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第3剂次接种生产厂家编码',
  `FPRODUCTNO_3` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第3剂次疫苗制品',
  `FSTATIONNAME_3` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTDATED_4` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第4剂次接种日期',
  `STATIONCODE_4` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第4剂次接种单位编码',
  `SUPCODE_4` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第4剂次接种街道编码',
  `COUNTYCODE_4` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第4剂次接种区县编码',
  `CITYCODE_4` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第4剂次接种地市编码',
  `FENTERPNO_4` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第4剂次接种生产厂家编码',
  `FPRODUCTNO_4` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '第4剂次疫苗制品',
  `FSTATIONNAME_4` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `serverupdatetime` datetime DEFAULT CURRENT_TIMESTAMP,
  `JZYS_1` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZYS_2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZYS_3` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZYS_4` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SEX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `fcrowdkindcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FLAG` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '0',
  PRIMARY KEY (`FCHILDNO`) USING BTREE,
  KEY `epi_xg_info_1` (`FPRODUCTNO_1`,`FSHOTDATED_1`) USING BTREE,
  KEY `epi_xg_info_2` (`FPRODUCTNO_2`,`FSHOTDATED_2`) USING BTREE,
  KEY `info_area_1` (`COUNTYCODE_1`,`SUPCODE_1`,`STATIONCODE_1`) USING BTREE,
  KEY `info_area_2` (`COUNTYCODE_2`,`SUPCODE_2`,`STATIONCODE_2`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;


-- epi_shaoxing.epi_xg_jzjl definition

CREATE TABLE `epi_xg_jzjl` (
  `GSD_CITYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GSD_COUNTYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GSD_SUPCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GSD_STATIONCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZD_CITYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZD_COUNTYCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZD_SUPCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZD_STATIONCODE` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BIRTH` datetime DEFAULT NULL,
  `fcrowdkindcode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZRQ` datetime DEFAULT NULL,
  `YMPH` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `JZYS` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `YMJG` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `REASON` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CANCELDATE` datetime DEFAULT NULL,
  `FCHILDNO` char(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FSHOTKIND` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '1',
  `FENTERPNO` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTDATED` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FREACTIONCODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPLACECODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUNDODATE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUNDODATED` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPRODUCTNO` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `USTATIONCODE` char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBACTID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FSOURCE` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FBATCHKEY` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUSEIMMUBILL` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FPRODUCTLISTCODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FLASTEDITDATETIME` datetime DEFAULT NULL,
  `FINPUTDATE` datetime DEFAULT NULL,
  `FMONITORCODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FFREECHARGE` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UISOUT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FWAITMINUTES` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `SERVERUPDATETIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `FSHOTWAYCODE` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTMEMO` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSHOTSPEC` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FSAMENESSFROM` char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FShotFromCard` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '儿童本条接种记录是否来自于IC卡  1(是)，0(否)',
  `FBatchExpiryDate` date DEFAULT NULL,
  `fpropertycode` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '疫苗属性代码：新冠06,国家免规01,强化05,应急03,其他非免规04,自动赋值暂无02',
  `fbactpaymode_cn` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '支付方式',
  `FOPERATESTATIONCODE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊编码',
  `FOPERATESTATIONNAME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊名称',
  `FVACCTYPECODE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `FUpdateStationCode` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修改单位编码',
  `FStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种单位国标码',
  `FOperateStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '当前操作接种门诊国标码（录入单位编码）',
  `FUpdateStationCode_CN` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '修改单位国标码',
  `FInputDateTime` datetime DEFAULT NULL COMMENT '录入时间',
  `FUpdateDateTime` datetime DEFAULT NULL COMMENT '修改时间',
  `FUpdateStationName` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '更新接种门诊名称',
  `FShotGuid` varchar(42) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '接种记录唯一ID(6位县区行政区划代码+GUID)',
  `VACCINATION` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VACCINATION_TIME` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `VACCINATION_COUNTY_GB` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `UPLOAD_DATE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TABU_CODE` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GXSJ` datetime DEFAULT NULL,
  PRIMARY KEY (`FCHILDNO`,`FBACTID`) USING BTREE,
  KEY `epi_xg_jzjl_1` (`JZRQ`,`FBACTID`,`FENTERPNO`) USING BTREE,
  KEY `epi_xg_jzjl_2` (`FMONITORCODE`) USING BTREE,
  KEY `epi_xg_jzjl_ind1` (`GSD_COUNTYCODE`) USING BTREE,
  KEY `epi_xg_jzjl_ind2` (`JZD_COUNTYCODE`) USING BTREE,
  KEY `epi_xg_jzjl_3` (`FShotGuid`) USING BTREE,
  KEY `epi_xg_jzjl_FStationCode_CN_IDX` (`FStationCode_CN`) USING BTREE,
  KEY `epi_xg_jzjl_SERVERUPDATETIME_IDX` (`SERVERUPDATETIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;