const BASE_URL = window.pathCommon;
export default {
  Login: `${BASE_URL}/user`,
  Common: `${BASE_URL}/common`,
  Setting: `${BASE_URL}/user`,
  Bbs: `${BASE_URL}/bbs`,
  InoculationUnit: `${BASE_URL}/InoculationUnit`,
  AreaManager: `${BASE_URL}/areaManager`,
  Hr: `${BASE_URL}/hr`,
  analysisRpt: `${BASE_URL}/analysisRpt`,
  xgRptInfo: `${BASE_URL}/xgRptInfo`,
  Role: `${BASE_URL}/role`,
  ChildrenSetting: `${BASE_URL}/childrenSetting`,
  StationManager: `${BASE_URL}/stationManager`,
  childCount: `${BASE_URL}/childCount`,
  noUpload: `${BASE_URL}/noUpload`,
  complain: `${BASE_URL}/complain`,
  childInfo: `${BASE_URL}/childInfo`,
  xgRptMonth: `${BASE_URL}/xgRptMonth`,
  xgAgeAndFenter: `${BASE_URL}/xgAgeAndFenter`,
  xgRptCrowdkind: `${BASE_URL}/xgRptCrowdkind`,
  xgRptProfession: `${BASE_URL}/xgRptProfession`,
  xgRptAge: `${BASE_URL}/xgRptAge`,
  xgRptArea: `${BASE_URL}/xgRptArea`,
  xgRptJzjl: `${BASE_URL}/xgRptJzjl`,
  xgRptNotVacc: `${BASE_URL}/xgRptNotVacc`,
  xgRptFinishVacc: `${BASE_URL}/xgRptFinishVacc`,
};
